### ISSUE TITLE
ISSUES with the main procedure

### ISSUE THREAD

**Issue by leontikos** [mmagnuski/senofag#10]
Stworzyłem małe podsumowanie wyników i komentarzy studentów:
https://docs.google.com/document/d/1EJS4VNvU7QPxjEvYc-keg6CIpknSgNK07MdYV779hFo/edit

**Wynika niestety z tego, że muszę jeszcze doprecyzować polecenie dla badanych**. Na razie tylko **Julia** robiła zadanie zgodnie z poleceniem (różnicowała między kolorami, a nie strzałkami, czy czymkolwiek innym).

**Myślę też nad tym, żeby może dodać prompt w procedurze, np. po pierwszym bloku, który informowałby osobę badaną o tym, że np. nie używa skali poczucia kontroli w wystarczająco zróżnicowany sposób, albo że powinna zwracać większą uwagę na kolory i między nimi różnicować swoje odpowiedzi.** 

Już mam kod, który wyciąga wyniki konkretnych bloków, więc teraz pozostaje decyzja, czy coś takiego dodawać po bloku. Wiem, że to mogłoby spowodować, że niektóre osoby miałyby trochę inne/więcej poleceń w trakcie badania, ale to też mógłbym odnotowywać w systemie. Tak, czy inaczej - najgorsza dla mnie sytuacja byłaby taka, gdybym znowu nie potwierdził efektu głównego prymy, mogłoby być trudno się z tego bronić, a już na pewno trudniej takie wyniki opublikować...

**Comment by mmagnuski** [comment]
Myślę że mylące może być dla badanych to, że piszesz w instrukcjach o ich "zadaniu", co może sugerować poprawne i niepoprawne odpowiedzi. Możesz spróbować większy nacisk kłaść na to aby próbowali odpowiadać intuicyjnie i nie rozkminiali za bardzo.

**Comment by mmagnuski** [comment]
> Myślę też nad tym, żeby może dodać prompt w procedurze, np. po pierwszym bloku, który informowałby osobę badaną o tym, że np. nie używa skali poczucia kontroli w wystarczająco zróżnicowany sposób, albo że powinna zwracać większą uwagę na kolory i między nimi różnicować swoje odpowiedzi.

Myślę że lepiej dobrze skroić instrukcje i dać ludziom swobodę korzystania ze skali po swojemu. I tak nie skodyfikujesz wszystkiego, a ludzi bez wariancji na skali możesz zawsze wywalać.

**Comment by mmagnuski** [comment]
A odnośnie pytania o strategię - to najlepiej wyjdzie jak człowiek wyposażony w kartkę o to będzie pytał. Procedura nie da Ci możliwości dopytania się o coś itp.
