### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by mmagnuski** [mmagnuski/senofag#3]
## important!
- [ ] zmienić numer telefonu z Mikołaja na mnie
- [ ] dodać info o żelowych czepkach i czasie trwania badania

- [ ] zmienić marker nr 4 na wyświetlenie efektu, ponieważ Win sprawdza port drukarki wysyłając marker
- [ ] dodać info do prime det task o tym, że jeszcze zostało tylko 5-8 minut badania

## questionnaire(s)
- [ ] add questions in the starting field: handedness, age, sex etc.
- [ ] add a question about distance measurement from the screen in the starting field
- [ ] ? add a SoA questionnaire **Leon** ?
- [ ] add an open field for reflections and a question about strategy in finding out personal SoA **Leon**

## stimuli
- [x] create the prime arrows @mmagnuski 
- [x] create the target arrows

## prime detection task
- [x] add SPACE as a "no prime" response
- [x] add slides about the SPACE key
- [x] add training for the prime detection task (NOT NECESSARY)

## scale
- [x] check scale descriptions and alternative for effect presentation **Leon**

## clean up trials dataframe creation
- [x] change prop to specific (fixed) value
- [x] settle on valid numer of trials
- [x] prime top or bottom (50% chance) (`pos` column in df)

## change trial presentation
- [x] markery
- [x] handle `pos`
- [x] randomize `fixTime` in block df creation, use the value in trial presentation
- [x] single-trial soa assesment
- [x] change key-waiting loop to `waitKeys` with time limit
- [x] evaluate response
- [x] present effect
- [x] set effect when/after creating block df

## meta
- [ ] partial shuffling (in blocks of `32` trials)
- [x] **create the prime detection procedure**
- [x] check if quit_check is working for the scale slide
- [x] erase effect and SoA assessment events from the prime detection procedure
- [x] add last question from the last slide (visibility of the prime)
- [x] add different groups procedure versions 
- [x] add training trials (20 trials maybe with 1 break after 10 trials (not necessarily though))
- [x] add saving after each trial
- [x] add the same trial type to the end of block df if incorrect response
- [x] continue presenting trials until trials in block_df run out
- [x] instructions and screens between trials **LEON**
- [x] **Each block0-3.csv should also save subject's number** (preferably in the filename as well)
- [x] `Trigger` class
- [x] `show_stim` general function
- [x] function / class that presents multiple trials (including breaks etc.)
- [x] save data (periodically)
- [x] check free-cued trials ratio in a block **LEON**

**Comment by mmagnuski** [comment]
@leontikos - tutaj mamy zadania z końca 2015 roku :)

**Comment by mmagnuski** [comment]
przeorganizowałem je trochę, jest kilka kwestii, które trzeba ustalić takie jak: ilość, proporcje triali, czasy prezentacji, przerwy, instrukcje itp.
Przynajmniej cześć dyskusji możemy przeprowadzić na githubie.

**Comment by mmagnuski** [comment]
@leontikos
Proponuję wrzucić na githuba np. plik `timings.md`, w który będzie opis czasów trwania wszystkich elementów (jak już wszystko będzie ustalone).

**Comment by leontikos** [comment]
## EXPERIMENT TIMELINE
| TIMELINE  | ms  |   | STRUCTURE  | #  |
|---|---|---|---|---|
|Fixation   | 1000-1500  |   | COLORS  | 4  |
| Prime  | 20  |   | TRIALS (per color)  | 160 |
| Fixation  | 40  |   | SUM (trials)  | 640 |
| Mask/Target  | 250  |   | BREAKS  | 10%  |
| Response  | max 1200  |   | SUM (time in min)  | 62.597  |
| Jittered delay  | 400-600  |   |  |   |
| Outcome  |  250 |   |  |  |
| Jittered delay  | 750-1250  |   |   |   |
| Agency rating  | max 1500  |   |   |   |
| CLEAR SCREEN  | 250-750  |   |   |   |
| SUM (avg)  | 5335|   |   |   |

**Comment by leontikos** [comment]
Pytania:
- co oznacza linijka 247 w stim.py? Czemu podany jest tak dziwny rozmiar?
- lin 20-21 settings.py: tu trzeba to zmienić?

**Comment by mmagnuski** [comment]
ad 247 - Instructions skopiowaliśmy z proc Oli, tam widocznie slajdy były w takim rozmiarze. Lepiej wygląda jak wyświetlasz pixel to pixel (bez reskalowania). Wpisz tyle ile mają Twoje obrazki z instrukcjami.

**Comment by mmagnuski** [comment]
ad linijki 20 - 21: nie rozumiem. To jest bardzo podstawowa funkcja - owija tylko visual.ShapeStim - którą wykorzystuje krzyżyk fiksacji.

**Comment by mmagnuski** [comment]
Tfu, nie zrozumiałem i zajrzałem w zły plik (`stim.py` a nie settings), sorry.
Jak chcesz inne klawisze niż 'l', 'd' - to tak, zmień. Proportions 80 - 80 powinny być ok. Tyle razy przemnażasz każde 4 kombinacje warunków dla free i 4 dla cued, 4 * 80 + 4 * 80 = 640 (a tyle triali chcesz mieć). Możesz dodać komentarz do tego ustawienia proportions, bo faktycznie nie jest jasne dlaczego akurat 80 - 80.

**Comment by mmagnuski** [comment]
Opcja do rozważenia - nie tasować całego df z pre-wygenerowanymi trialami, tylko zapewniać, że w ramach jakiejś wielokrotności 8 będą wszystkie podstawowe warunki. Wtedy byśmy tasowali kazdy segment np. 24 albo 32 triali. A więc nawet jak by komuś się popsuł sygnał w połowie badania albo wybiegł z krzykiem to jesteśmy w dobrej sytuacji bo mamy równe proporcje warunków.

**Comment by mmagnuski** [comment]
Możemy się umówić na niedługo albo weekend na procedurę (moją i Twoją ;) ).
Może ruszymy równocześnie i będziemy współdzielić pokój do badań, czepek oraz asystentów (a kto wie - może osoby badane?). Man, jakbyśmy współdzielili osoby badane, to miałbyś skany strukturalne do swojego badania bez zbytniego czekania! Ponadto moje ogarnianie skanów by posuwało do przodu obywda badania na raz.

**Comment by mmagnuski** [comment]
@leontikos obczaj `experiment_info.md`, które dodałem, teraz wszystkie techniczne informacje są w jednym pliku. Można do tego dodać nieco narracji i opis badania gotowy.

**Comment by mmagnuski** [comment]
To już chyba zamknięta sprawa skoro doktorat jest napisany. :)

**Comment by leontikos** [comment]
No już tylko poprawienie doktoratu oraz stworzenie profesjonalnej publikacji :P
