### ISSUE TITLE
Problem with prime vs target position in the prime detection task

### ISSUE THREAD

**Issue by leontikos** [mmagnuski/senofag#8]
I've noticed that sometimes the prime has a different position than the target (but only in the prime detection task) - sometimes the prime has -5 deg position and the target 5 deg, and vice versa (vis-a-vis, ergo, et cetera).

**Comment by mmagnuski** [comment]
A, ok zobacz setPos z normalnego triala. Ale mozemy to w ogole zmienic tak ze gorne i dolne sa pregenerowane. Bo obecnie przez buga w psychopy musimy tworzyc nowy obiekt przy kazdej zmianie pozycji.
