### ISSUE TITLE
ISSUES with the data analysis code

### ISSUE THREAD

**Issue by leontikos** [mmagnuski/senofag#9]
Miko, nie wiem czemu nie chcą mi się generować subploty w pliku:
https://github.com/mmagnuski/senofag/blob/master/notebooks/Experiment%202%20DATA%20ANALYSIS.ipynb

Spójrz na sekcję:
`SoA rating divided by blocks for each subject - FIXME`
Coś tam musi być nie tak, albo to jest bug w Pythonie (?)
Powstaje rycina, ale nie wypełnia się plotami...

**Comment by mmagnuski** [comment]
jeżeli bug to w seabornie albo matplotlibie, ale nie jest to jasne, musiałbyś uprościć przykład aby problem pojawiał się przy minimalnej liczbie linijek kodu.
Póki co podejrzane jest to że punkty w legendzie wyświetlają się inaczej - może używasz punktorów (markerów), które są bez wypełnienia a mają linewidth=0? Albo może query, których używasz dają Ci puste dane?

**Comment by mmagnuski** [comment]
BTW zamiast:
```python
df.query('ifcorr == True').query('subject_nr == "{}"'.format(name))
```
możesz robić:

```python
df.query('ifcorr == True & subject_nr == "{}"'.format(name))
```
